version:
  - 3.11        # [not riscv64]
  - 3.12        # [not riscv64]
  - 3.13        # [not riscv64]
  - 3.13        # [not riscv64]
  - 3.14
  - 3.14
  - 3.15
  - 3.15
py_impl:
  - cpython     # [not riscv64]
  - cpython     # [not riscv64]
  - cp313       # [not riscv64]
  - cp313t      # [not riscv64]
  - cp314
  - cp314t
  - cp315
  - cp315t
freethreading:
  - no          # [not riscv64]
  - no          # [not riscv64]
  - no          # [not riscv64]
  - yes         # [not riscv64]
  - no
  - yes
  - no
  - yes
channel_sources:
  - conda-forge # [not riscv64]
  - conda-forge # [not riscv64]
  - conda-forge # [not riscv64]
  - conda-forge # [not riscv64]
  - conda-forge
  - conda-forge
  - conda-forge,conda-forge/label/python_rc
  - conda-forge,conda-forge/label/python_rc
cross_target_platform:
  - "linux-64"
  - "linux-ppc64le"
  - "linux-aarch64"
  - "linux-riscv64"
  - "osx-64"
  - "osx-arm64"
zip_keys:
  - - version
    - py_impl
    - channel_sources
    - freethreading
