{% set build_number = 53 %}
{% if cross_target_platform is undefined %}
{% set cross_target_platform = "linux-64" %}
{% endif %}

package:
  name: cross-python_{{ cross_target_platform }}
  version: {{ version }}

build:
  number: {{ build_number }}
  string: {{ build_number }}_{{ py_impl }}
  skip: True  # [win]
  skip: True  # [cross_target_platform == target_platform]
  skip: True  # [cross_target_platform == "osx-arm64" and (py_impl == "73_pypy" or version == "3.7")]
  run_exports:
    strong:
      - python {{ version }}.* *_{{ py_impl }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
  run:
    - python {{ version }}.* *_{{ py_impl }}
    - crossenv >=1.1.4
    - rsync
    - sed
{% if cross_target_platform.startswith("osx-") %}
    - clangxx_impl_{{ cross_target_platform }}
{% endif %}
{% if cross_target_platform.startswith("linux-") %}
    - gxx_impl_{{ cross_target_platform }}
{% endif %}

{% if cross_target_platform.startswith("linux-") and version != "3.9" %}
test:
  commands:
    - test -f $PREFIX/etc/conda/activate.d/activate_z-cross-python_{{ cross_target_platform }}.sh
    - echo {{ freethreading }}
{% endif %}

about:
  home: https://github.com/conda-forge/cross-python-feedstock
  license: LicenseRef-OTHER
  summary: 'A meta-package to set up a cross compiling env for python in conda-build'

extra:
  recipe-maintainers:
    - chrisburr
    - isuruf
  feedstock-name: cross-python
